# SPDX-FileCopyrightText:  gb-open-market-model contributors
#
# SPDX-License-Identifier: CC0-1.0


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  name: "GB"

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: overnight

scenario:
  clusters:
  - 100
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  - 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries:
- BE
- DK
- FR
- GB
- IE
- NL
- 'NO'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  focus_weights: {NL: 0.01, 'NO': 0.01, BE: 0.01, DK: 0.01, IE: 0.02, FR: 0.03, GB: 0.91}

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solving
solving:
  options:
    load_shedding: false
  solver:
    name: gurobi
    options: gurobi-default
