# SPDX-FileCopyrightText: Open Energy Transition gGmbH and contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0


target_crs: "EPSG:27700"
area_loss_tolerance_percent: 0.01 # percentage of area loss tolerated when splitting regions
min_region_area: 1000000 # minimum area of a region in square meters (1 km²) for keeping it after splitting
