# SPDX-FileCopyrightText: Open Energy Transition gGmbH and contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0


target_crs: "EPSG:27700"
area_loss_tolerance_percent: 0.01 # percentage of area loss tolerated when splitting regions
min_region_area: 1000000 # minimum area of a region in square meters (1 km²) for keeping it after splitting

# Manual region merging configuration
region_operations:
  # Regions to split before merging
  splits:
    - region: 6
      type: "vertical"
      coordinate: -2.48
    - region: 5
      type: "vertical" 
      coordinate: -1.93
    - region: 8
      type: "vertical"
      coordinate: -2.48
    - region: 46
      type: "horizontal"
      coordinate: 53.1
  
  # Groups of regions to merge together
  merge_groups:
    - [61, 64]
    - [47, 48, 49]
    - [54, 55, 56]
    - [52, 53]
    - [41, 43, "46s"]
    - [77, 78, 79]
    - [40, 44, 45]
    - [13, 16, 17]
    - [80, 81, 82, 83]
    - [18, 19, 20, 21, 22, 23, 24, 31, 32, 33, 34, 94, 95, 96, 97, 98]
    - [2, 3, 91, 92]
    - [14, 15, 25, 26, 27, 28, 29, 30, 35, 36, 37, 38]
    - [62, 63, 86, 87, 88]
    - [65, 66, 67, 68, 69, 70, 71, 72, 73, 84, 85]
    - [10, "6wn", 11, 12, "8w"]
    - ["6e", "6ws", 7, 9]
    - [39, 99]
    - [74, 75, 76]
    - [4, "5w"]
