# SPDX-FileCopyrightText:  gb-open-market-model contributors
#
# SPDX-License-Identifier: MIT

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  name: "GB"

urls:
  gb-etys-boundaries: https://api.neso.energy/dataset/997f4820-1ad4-499b-b1fe-4b8d3d7fbc72/resource/e914fcec-1dc9-4f1f-97e7-59c0d9521bea/download/etys-boundary-gis-data-mar25.zip
  transmission-availability: https://www.neso.energy/document/211021/download
  fes-workbook: https://www.neso.energy/document/199971/download # FES 2021 workbook
  gsp-coordinates: https://api.neso.energy/dataset/963525d6-5d83-4448-a99c-663f1c76330a/resource/41fb4ca1-7b59-4fce-b480-b46682f346c9/download/fes2021_regional_breakdown_gsp_info.csv
target_crs: "EPSG:27700"
area_loss_tolerance_percent: 0.01 # percentage of area loss tolerated when splitting regions
min_region_area: 1000000 # minimum area of a region in square meters (1 km²) for keeping it after splitting

# Manual region merging configuration
region_operations:
  # Regions to split before merging
  splits:
  - region: 6
    type: "vertical"
    coordinate: -2.48
  - region: 5
    type: "vertical"
    coordinate: -1.93
  - region: 8
    type: "vertical"
    coordinate: -2.48
  - region: 46
    type: "horizontal"
    coordinate: 53.1

  # Groups of regions to merge together
  merge_groups:
  - [61, 64]
  - [47, 48, 49]
  - [54, 55, 56]
  - [52, 53]
  - [41, 43, "46s"]
  - [77, 78, 79]
  - [40, 44, 45]
  - [13, 16, 17]
  - [80, 81, 82, 83]
  - [18, 19, 20, 21, 22, 23, 24, 31, 32, 33, 34, 94, 95, 96, 97, 98]
  - [2, 3, 91, 92]
  - [14, 15, 25, 26, 27, 28, 29, 30, 35, 36, 37, 38]
  - [62, 63, 86, 87, 88]
  - [65, 66, 67, 68, 69, 70, 71, 72, 73, 84, 85]
  - [10, "6wn", 11, 12, "8w"]
  - ["6e", "6ws", 7, 9]
  - [39, 99]
  - [74, 75, 76]
  - [4, "5w"]

fes-sheet-config:
  SV.34:
    usecols: "I:AN"
    skiprows: 5
    index_col: 0
    header: 0
    rename:
      index: scenario
      columns: year

  BB1:
    usecols: "A:C,E,H:AK" # Ignore columns: "Baseline (2020)", "Share of GSP" (empty), "DNO License Area"
    skiprows: 0
    index_col: [0, 1, 2, 3]
    header: 0
    rename:
      columns: year

  BB2:
    usecols: "A:E"
    skiprows: 2
    index_col: [0,1,3]
    header: 0
    rename:
      columns: Parameter

fes:
  fes_scenario: 'Leading The Way'
  year: 2021